# Copyright (c) 2026 RioPlay <rioplay@rioplay.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render LEXICON-SOURCES.md from a provenance sidecar.

The sidecar is a JSON object:
  {
    "built_at": "<ISO timestamp>",
    "sources":  ["oewn", "moby", ...],
    "edges": {
      "<subj>|<label>|<obj>": {
        "kind":      "imported" | "derived",
        "sources":   ["oewn", "moby"] | null,
        "method":    "string or null",
        "agreement": 2
      }
    }
  }

Output: a Markdown document (repo-root LEXICON-SOURCES.md) with:
  1. A generated-by notice.
  2. A "Sources in current build" table (Source | License | Shippable? | Edge count).
  3. An "Attribution requirements" section.
  4. An "Excluded from shipping" table (non-shippable sources).

If the sidecar is absent, the script prints an informational message and exits 0.

Usage:
    python3 scripts/gen_lexicon_manifest.py \\
        --sidecar ~/.cache/aden/lexicon-provenance.json \\
        --out     LEXICON-SOURCES.md
"""
import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

# Verified license metadata for known lexical sources.
# Shippable = compatible with AGPL-3.0-or-later (no ShareAlike virality issues).
_SOURCE_META: dict[str, dict] = {
    "oewn": {
        "label": "Open English WordNet (OEWN)",
        "license": "CC-BY-4.0 + WordNet license",
        "shippable": True,
        "attribution": (
            "Dual attribution required: cite Princeton WordNet (retain the "
            "Princeton notice; do not use 'Princeton' in advertising) AND "
            "the Open English WordNet team (https://github.com/globalwordnet/english-wordnet)."
        ),
    },
    "moby": {
        "label": "Moby Thesaurus II",
        "license": "Public Domain",
        "shippable": True,
        "attribution": "No attribution required (Public Domain).",
    },
    "roget": {
        "label": "Roget's Thesaurus 1911",
        "license": "Public Domain",
        "shippable": True,
        "attribution": "No attribution required (Public Domain).",
    },
    "webster1913": {
        "label": "Webster's Dictionary 1913 (Project Gutenberg #29765)",
        "license": "Public Domain",
        "shippable": True,
        "attribution": "No attribution required (Public Domain).",
    },
    "wikidata": {
        "label": "Wikidata Lexemes",
        "license": "CC0",
        "shippable": True,
        "attribution": "No attribution required (CC0).",
    },
    "wordnet": {
        "label": "Princeton WordNet",
        "license": "WordNet license",
        "shippable": True,
        "attribution": (
            "Retain the Princeton WordNet copyright notice in distributions. "
            "Do not use 'Princeton University' in advertising without written permission."
        ),
    },
    "conceptnet": {
        "label": "ConceptNet",
        "license": "CC-BY-SA 4.0",
        "shippable": False,
        "attribution": (
            "ShareAlike clause is incompatible with AGPL-3.0-or-later. "
            "Excluded from shipping."
        ),
    },
}

_EXCLUDED = ["conceptnet"]


def _count_edges_per_source(edges: dict) -> dict[str, int]:
    """Count how many edges each source contributes."""
    counts: dict[str, int] = defaultdict(int)
    for edge_data in edges.values():
        srcs = edge_data.get("sources") or []
        for src in srcs:
            counts[src] += 1
    return dict(counts)


def render(sidecar: dict, built_at: str) -> str:
    """Render the Markdown document from the parsed sidecar."""
    sources_in_build: list[str] = sidecar.get("sources", [])
    edges: dict = sidecar.get("edges", {})
    edge_counts = _count_edges_per_source(edges)

    lines: list[str] = []

    lines.append("# Lexicon Sources")
    lines.append("")
    lines.append(
        f"Generated by `scripts/gen_lexicon_manifest.py` from provenance sidecar. "
        f"Build timestamp: {built_at}."
    )
    lines.append("")
    lines.append(
        "Do not edit this file by hand. Regenerate with:"
    )
    lines.append("")
    lines.append("```")
    lines.append("python3 scripts/gen_lexicon_manifest.py")
    lines.append("```")
    lines.append("")

    # Sources table.
    lines.append("## Sources in current build")
    lines.append("")
    lines.append("| Source | License | Shippable? | Edge count |")
    lines.append("| ------ | ------- | ---------- | ---------- |")

    shippable_sources = []
    for src_id in sources_in_build:
        if src_id in _EXCLUDED:
            continue
        meta = _SOURCE_META.get(src_id)
        if meta is None:
            label = src_id
            license_str = "Unknown"
            shippable_str = "Unknown"
        else:
            label = meta["label"]
            license_str = meta["license"]
            shippable_str = "Yes" if meta["shippable"] else "No"
            if meta["shippable"]:
                shippable_sources.append(src_id)

        count = edge_counts.get(src_id, 0)
        lines.append(f"| {label} | {license_str} | {shippable_str} | {count} |")

    lines.append("")

    # Attribution requirements.
    lines.append("## Attribution requirements")
    lines.append("")
    lines.append(
        "The following attribution notices apply to shippable sources included "
        "in this build."
    )
    lines.append("")

    for src_id in shippable_sources:
        meta = _SOURCE_META.get(src_id)
        if meta is None:
            continue
        lines.append(f"### {meta['label']}")
        lines.append("")
        lines.append(meta["attribution"])
        lines.append("")

    # Excluded sources.
    lines.append("## Excluded from shipping")
    lines.append("")
    lines.append(
        "The following sources are excluded from distribution due to license "
        "incompatibility with AGPL-3.0-or-later."
    )
    lines.append("")
    lines.append("| Source | License | Reason |")
    lines.append("| ------ | ------- | ------ |")

    for src_id in _EXCLUDED:
        meta = _SOURCE_META.get(src_id)
        if meta is None:
            continue
        reason = meta["attribution"]
        lines.append(f"| {meta['label']} | {meta['license']} | {reason} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Render LEXICON-SOURCES.md from a provenance sidecar."
    )
    ap.add_argument(
        "--sidecar",
        default=str(Path.home() / ".cache/aden/lexicon-provenance.json"),
        help="Path to lexicon-provenance.json (default: %(default)s)",
    )
    ap.add_argument(
        "--out",
        default=str(Path(__file__).parent.parent / "LEXICON-SOURCES.md"),
        help="Output Markdown file (default: repo-root LEXICON-SOURCES.md)",
    )
    args = ap.parse_args()

    sidecar_path = Path(args.sidecar)
    if not sidecar_path.exists():
        print(
            f"Sidecar not found at {sidecar_path}. "
            "Run the lexicon importer first to generate it."
        )
        sys.exit(0)

    with sidecar_path.open(encoding="utf-8") as fh:
        sidecar = json.load(fh)

    built_at = sidecar.get("built_at", "unknown")
    content = render(sidecar, built_at)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
