#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Refresh Cargo attribution while preserving Aden's maintained legal preamble."""
import argparse
import json
from pathlib import Path
import subprocess

MARKER = "# Third-Party Dependencies\n"


def render_notice(original, metadata):
    if original.count(MARKER) != 1:
        raise ValueError("NOTICE must contain exactly one third-party section marker")
    packages = [p for p in metadata["packages"] if p.get("source")]
    if not packages:
        raise ValueError("Refusing to replace attribution with an empty dependency list")
    rows = []
    for package in sorted(packages, key=lambda p: (p["name"], p["version"])):
        if not package.get("license"):
            raise ValueError(f"Missing license metadata: {package['name']} {package['version']}")
        rows.append(f"### {package['name']} v{package['version']}\n\n"
                    f"- **License**: {package['license']}\n"
                    f"- **Repository**: {package.get('repository') or 'Not specified upstream'}\n")
    return original.split(MARKER)[0] + MARKER + "\n" + (
        "Generated by `python scripts/update_notice.py` from locked Cargo metadata\n"
        "with all workspace features enabled. Includes optional, development and\n"
        "platform-specific dependencies; not every entry ships in every binary.\n\n"
        "## Dependencies with Licenses\n\n"
    ) + "\n".join(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on drift without writing")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--all-features", "--format-version", "1"],
        cwd=root, text=True, encoding="utf-8"))
    notice = root / "NOTICE.md"
    original = notice.read_text(encoding="utf-8")
    rendered = render_notice(original, metadata)
    if args.check:
        if original != rendered:
            raise SystemExit("NOTICE.md has drifted; run python scripts/update_notice.py")
        print("NOTICE.md matches locked dependency metadata")
    else:
        notice.write_text(rendered, encoding="utf-8")
        print("Updated dependency attribution; maintained legal preamble preserved")


if __name__ == "__main__":
    main()
