// Copyright (c) 2026 RioPlay <rioplay@rioplay.dev>
// All rights reserved.
//
// Aden: A Dense Referential Context Compiler
// Original author and maintainer: RioPlay
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
use std::fmt::Write;
use std::fs::File;
use std::io;
use std::io::Write as _;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};
use aden_core::Table;

pub fn generate_stub(anchor: &str, title: &str, sig_table: &Table, source_hash: &str) -> String {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let mut output = String::new();
    writeln!(output, ":source_hash: {}", source_hash).unwrap();
    writeln!(output, ":last-verified: {}", timestamp).unwrap();
    writeln!(output, ":node-type: function").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "[[{}]]", anchor).unwrap();
    writeln!(output, "= {}", title).unwrap();
    writeln!(output, "== Signature").unwrap();
    emit_table(&mut output, sig_table);
    writeln!(output, "== Invariants").unwrap();
    writeln!(output).unwrap();
    writeln!(
        output,
        "agent-note::STUB[Auto-generated by aden-heal. Review before removing this note.]"
    )
    .unwrap();

    output
}

fn emit_table(out: &mut String, table: &Table) {
    writeln!(out, "|===").unwrap();
    if !table.headers.is_empty() {
        for h in &table.headers {
            write!(out, "|{}", h).unwrap();
        }
        writeln!(out).unwrap();
    }
    for row in &table.rows {
        for cell in row {
            write!(out, "|{}", cell).unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "|===").unwrap();
}

pub fn write_stub(path: &Path, content: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    file.write_all(content.as_bytes())?;
    Ok(())
}
