// Copyright (c) 2026 RioPlay <rioplay@rioplay.dev>
// SPDX-License-Identifier: AGPL-3.0-or-later

use aden_core::Table;
use std::fmt::Write;
use std::fs::File;
use std::io;
use std::io::Write as _;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

pub fn generate_stub(anchor: &str, title: &str, sig_table: &Table, source_hash: &str) -> String {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let mut output = String::new();
    writeln!(output, ":source_hash: {}", source_hash).unwrap();
    writeln!(output, ":last-verified: {}", timestamp).unwrap();
    writeln!(output, ":node-type: function").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "[[{}]]", anchor).unwrap();
    writeln!(output, "= {}", title).unwrap();
    writeln!(output, "== Signature").unwrap();
    emit_table(&mut output, sig_table);
    writeln!(output, "== Invariants").unwrap();
    writeln!(output).unwrap();
    writeln!(
        output,
        "agent-note::STUB[Auto-generated by aden-heal. Review before removing this note.]"
    )
    .unwrap();

    output
}

fn emit_table(out: &mut String, table: &Table) {
    writeln!(out, "|===").unwrap();
    if !table.headers.is_empty() {
        for h in &table.headers {
            write!(out, "|{}", h).unwrap();
        }
        writeln!(out).unwrap();
    }
    for row in &table.rows {
        for cell in row {
            write!(out, "|{}", cell).unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "|===").unwrap();
}

pub fn write_stub(path: &Path, content: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    file.write_all(content.as_bytes())?;
    Ok(())
}
