[package]
name = "aden-parse"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aden-core = { path = "../aden-core" }
tree-sitter = { version = "0.26", optional = true }
tree-sitter-language-pack = { version = "1.8", optional = true }

[dev-dependencies]
serde_json = "1.0"
tempfile = "3"

[features]
default = ["tree-sitter", "generic"]
generic = ["tree-sitter", "tree-sitter-language-pack"]
